spring.application.name=caostone2

spring.datasource.url=jdbc:mysql://localhost:3306/myfitDB


spring.datasource.username=root

spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.show-sql=true

spring.jpa.generate-ddl=true

spring.jpa.hibernate.ddl-auto=update

spring.web.error.include-message=always

spring.web.error.include-stacktrace=always

openai.api-key=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